### ISSUE TITLE
projectile-find-file shows moved file twice

### ISSUE THREAD

**Issue by wedens** [bbatsov/projectile#715]
I moved some file using dired, invalidated projectile cache (even tried to remove cache file manually), but projectile still shows file in old and new location. projectile-purge-file-from-cache on old location says file is not in cache.

**Comment by Jickelsen** [comment]
I am experiencing the same issue.

**Comment by Silex** [comment]
Even with <kbd>C-u C-c p f</kbd> ?

**Comment by Jickelsen** [comment]
Yes, the old path still shows up next to the new one.

**Comment by bbatsov** [comment]
I cannot imagine how this could happen. Especially without caching involved. More info would be helpful.

**Comment by tuhdo** [comment]
At this time the issue is opened, invalidate cache did not clean up recentf files and as a result, if Projectile is sorted using `recentf`, then non-existent files from recentf are also included. Now this was fixed.

**Comment by kluge** [comment]
I am experiencing an issue that sounds the same with projectile from MELPA today.

Moved file shows with the the new and old locations.

I even disabled caching and now projectile-enable-caching is nil. The old locations still show up. I don't have any idea on how to debug further.
